#****ATTENTION****#
#****ATTENTION****#
#****ATTENTION****#
#****ATTENTION****#
#****ATTENTION****##****ATTENTION****##****ATTENTION****##****ATTENTION****##****ATTENTION****#
#WORK IN PROGRESS, THIS IS NOT A WORKING AUTOMATION YET!!!!!!  DO NOT DOWNLOAD OR ATTEMPT TO INSTALL INTO YOUR HOME ASSISTANT!!!!  
#****ATTENTION****##****ATTENTION****##****ATTENTION****##****ATTENTION****##****ATTENTION****#
#****ATTENTION****#
#****ATTENTION****#
#****ATTENTION****#
#****ATTENTION****#
#****ATTENTION****#

blueprint:
  name: Motion Actions based on Time of Day
  description: Perform different actions when triggered by a motion sensor.  Based on the time of day, perform a differnt task. 
  domain: automation
  source_url: https://github.com/mharris1984/HA-Blueprints/blob/main/Motion_Actions-BasedonTIME.yaml
  input:
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    time1_on:
      name: Time Number 1 - Time to turn ON
      selector:
        time:
    time1_off:    
      name: Time Number 1 - Time to turn OFF
      selector:
        time:
    device1_entity:
      name: Device Number 1 - Device to Control
      selector:
        entity:

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input motion_entity
    from: "off"
    to: "on"
  - platform: time
    at: !input time1_on
  - platform: time
    at: !input time1_off

action:
  - alias: "Time Number 1 Actions"
    service: !input time1_on
    target: !input switch_target
  - alias: "Wait until there is no motion from device"
    wait_for_trigger:
      platform: time
      entity_id: !input time1_off
      from: "on"
      to: "off"
  - alias: "Wait the number of seconds that has been set"
    delay: !input no_motion_wait
  - alias: "Turn off the switch"
    service: switch.turn_off
    target: !input switch_target
